name: LunarClient-API
version: ${git.commit.id.abbrev}
description: A server interface for the Lunar Client
author: Moonsworth LLC Development Team
main: com.lunarclient.bukkitapi.LunarClientAPI
load: STARTUP
website: https://www.lunarclient.com/
